### ISSUE TITLE
No Tree apears

### ISSUE THREAD

**Issue by hnorkowski** [Knechtcraft/treepers-sponge#3]
Works fine but no trees apears

`[Server thread/ERROR] [Sponge]: Could not pass ExplosionEvent$Pre$Impl to Plugin{id=treepers, name=Treepers, version=5.1.3, description=Stops Creepers from destroying blocks and plants trees instead., url=https://github.com/Felfio/treepers-sponge, authors=[Felfio], source=/home/tavaro/mc2/mods/treepers-5.1.3.jar}
java.lang.NoSuchMethodError: org.spongepowered.api.world.World.getBiome(II)Lorg/spongepowered/api/world/biome/BiomeType;
        at org.felfio.sponge.treepers.Treepers.plantTree(Treepers.java:143) ~[Treepers.class:?]
        at org.felfio.sponge.treepers.Treepers.onExplode(Treepers.java:110) ~[Treepers.class:?]
        at org.spongepowered.common.event.listener.PreListener_Treepers_onExplode9.handle(Unknown Source) ~[?:?]
        at org.spongepowered.common.event.RegisteredListener.handle(RegisteredListener.java:95) ~[RegisteredListener.class:1.11-2195-6.0.0-BETA-2001]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:301) [SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2001]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:330) [SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2001]
        at org.spongepowered.mod.event.SpongeModEventManager.post(SpongeModEventManager.java:314) [SpongeModEventManager.class:1.11-2195-6.0.0-BETA-2001]
        at org.spongepowered.common.SpongeImpl.postEvent(SpongeImpl.java:144) [SpongeImpl.class:1.11-2195-6.0.0-BETA-2001]
        at net.minecraft.world.WorldServer.func_72885_a(WorldServer.java:1517) [lw.class:?]
        at net.minecraft.world.WorldServer.triggerInternalExplosion(WorldServer.java:1129) [lw.class:?]
        at org.spongepowered.common.interfaces.entity.explosive.IMixinExplosive.detonate(IMixinExplosive.java:53) [IMixinExplosive.class:1.11-2195-6.0.0-BETA-2001]
        at net.minecraft.entity.monster.EntityCreeper.redirect$onExplode$zeo003(SourceFile:205) [zo.class:?]
        at net.minecraft.entity.monster.EntityCreeper.func_146077_cc(SourceFile:248) [zo.class:?]
        at net.minecraft.entity.monster.EntityCreeper.func_70071_h_(SourceFile:158) [zo.class:?]
        at org.spongepowered.common.event.tracking.TrackingUtil.tickEntity(TrackingUtil.java:150) [TrackingUtil.class:1.11-2195-6.0.0-BETA-2001]
        at net.minecraft.world.WorldServer.redirect$onCallEntityUpdate$zjj000(WorldServer.java:1319) [lw.class:?]
        at net.minecraft.world.World.func_72866_a(World.java:85) [ajq.class:?]
        at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:840) [lw.class:?]
        at net.minecraft.world.World.func_72870_g(World.java:1957) [ajq.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1182) [ajq.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:711) [lw.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:720) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:384) [lh.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:624) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:482) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
`

**Comment by EvilCh33z** [comment]
Same here. 

Would post the log but it's almost exactly the same

**Comment by Kruemelkatze** [comment]
Thanks for reporting. I'm going to have a look on this!
What Sponge version are you using? Looks like they changed the API signature of some methods Treepers uses.
